### ISSUE TITLE
Missing step from setup on OHW jupyterhub tutorial

### ISSUE THREAD

**Issue by emiliom** [oceanhackweek/ohw-resources#18]
@callumrollo I'm porting your issue here (from https://github.com/oceanhackweek/oceanhackweek.github.io/issues/79), where it belongs. Thanks for submitting this!!

The tutorial page that details how to work with tutorials on the OHW jupyterhub refers to a "Step 4" in the final paragraph

"you MUST complete Step 4 to save the files to your local machine if you would like continued access to them"

However, I cannot find Step 4 on the page.

https://oceanhackweek.github.io/ohw-resources/tutorials/getting_started/

**Comment by emiliom** [comment]
The page is https://oceanhackweek.github.io/ohw-resources/tutorials/getting_started/

**Comment by callumrollo** [comment]
Thanks for moving this Emilio, sorry I submitted to the wrong repo! Clearly should've paid closer attention during the github intro session.

**Comment by emiliom** [comment]
No worries at all! Our web presence can be confusing. You submitted the issue, and that's what matters. I'll fix it today -- unless I forget :roll_eyes:
