### ISSUE TITLE
Automating mkdocs gh-pages build

### ISSUE THREAD

**Issue by emiliom** [oceanhackweek/ohw-resources#2]
Currently the `sites` files on the `gh-pages` branch are not built automatically. The workflow for now will be something like this:

- People submit PR's with changes to content (markdown files and mkdocs.yml). 
- Review PR and merge into master
- Someone (initially, Emilio) pulls the latest master into local clone, then uses `mkdocs gh-deploy` to deploy to `gh-pages` (in my case: `mkdocs gh-deploy -r upstream`

The most common options for having gh-pages rebuilt automatically seem to be GitHub Actions ([see these instructions](https://github.com/marketplace/actions/deploy-mkdocs)) and setting up a CI.
- Another [writeup showing the use of GitHub Actions, but via a more complex Docker-based setup](https://medium.com/better-programming/build-a-blog-with-github-and-mkdocs-cf47914affa7)
- [A write on setting up Travis CI (I think)](https://mwop.net/blog/2016-01-29-automating-gh-pages.html)

I'll try to get GitHub Actions implemented. @ocefpaf if you can help, great, but you're probably already maxed out with OHW

**Comment by emiliom** [comment]
@leewujung's addition of the GH Action to auto-build the site (`gh_pages`) is now online!! Initial PR (#4) was corrected and finalized by #5

**Comment by emiliom** [comment]
@ocefpaf the GH Actions auto-build is now working. But I'm curious [about this warning ("annotation")](https://github.com/oceanhackweek/ohw-learning-resources/actions/runs/188996148):
```
Unexpected input(s) 'GITHUB_TOKEN', valid inputs are ['installer-url', 'miniconda-version', 'conda-version', ...
```
It seems to have no real impact, but it'd be nice to get rid of it. Do you think it's due to this line:
https://github.com/oceanhackweek/ohw-learning-resources/blob/master/.github/workflows/main.yml#L22
Looks like it's not doing anything and doesn't belong there.

**Comment by ocefpaf** [comment]
Not sure. I never used the miniconda GH action before. We can ask upstream.

**Comment by emiliom** [comment]
Thanks. No big deal; like I said, it's working.

**Comment by leewujung** [comment]
Thanks for noticing the warning! It is a leftover input argument to [MkDocs GH action](https://github.com/marketplace/actions/deploy-mkdocs) -- which didn't work for us because our build requires markdownextradata. That's why I went the [setup-miniconda](setup-miniconda) route to get both mkdocs and markdownextradata installed and run the build.
