### ISSUE TITLE
Include nbgitpuller link for tutorials

### ISSUE THREAD

**Issue by abkfenris** [oceanhackweek/ohw-resources#40]
[nbgitpuller](https://jupyterhub.github.io/nbgitpuller/) allows us to specify a link that will clone and pull the tutorial repo. It will also bring a users repo up to date without stomping over their changes.

https://ohw.pilot.2i2c.cloud/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Foceanhackweek%2Fohw-tutorials&urlpath=lab%2Ftree%2Fohw-tutorials%2F&branch=master

Hat tip to @ocefpaf for getting nbgitpuller setup and configuring the link for tutorials.

**Comment by emiliom** [comment]
I haven't used nbgitpuller myself, much. Scanning the ["When to use nbgitpuller?"](https://jupyterhub.github.io/nbgitpuller/#when-to-use-nbgitpuller) section, it says that it's best to avoid mixing nbgitpuller and direct git commands. So, the plan is to provide the above https://ohw.pilot.2i2c.cloud gitpuller link for cloning and updating tutorial content from the repo into each user's jupyterhub space, and rely on that exclusively . No direct use of git for tutorials, right?

Then, what needs to be done is to overhaul the content of https://oceanhackweek.github.io/ohw-resources/tutorials/getting_started/ to point to the nbgitpuller link and briefly explain what it does, right?

**Comment by paigem** [comment]
Very good point @emiliom re mixing git commands and nbgitpuller. 

For tutorials it could make sense to use nbgitpuller, since users presumably will not be contributing back to that repo. But, users will want to use git themselves when doing project work. If it's not advised to mix git and nbgitpuller, then does it make more sense to stick with using git commands instead of using nbgitpuller?

**Comment by abkfenris** [comment]
I'm pretty sure that nbgitpuller is targeting a specific folder to pull the tutorials into. Since projects should be in their own directories, then I believe it should not interfere. 

The big thing it manages for the tutorials are dealing with if a participant runs a notebook, and the upstream one changes too, then nbgitpuller can still update the rest of the tutorials without having to coach the participants through stashing and restoring their changes.

**Comment by emiliom** [comment]
Still need to overhaul https://oceanhackweek.github.io/ohw-resources/tutorials/getting_started/ to point to the nbgitpuller link and briefly explain what it does. And/or point to the description Alex added to https://oceanhackweek.github.io/ohw-resources/prep/jupyterhub/ just now
